### ISSUE TITLE
When i try and check Australia I get:

### ISSUE THREAD

**Issue by odscjames** [open-contracting/ocdsdata#119]
From #100 

```
 - checking ...
Traceback (most recent call last):
  File "ocdsdata-cli", line 177, in <module>
    main()
  File "ocdsdata-cli", line 157, in main
    instance.run_check()
  File "/home/ocdsdata/ocdsdata/ocdsdata/base.py", line 280, in run_check
    check_file(source_session_id, data)
  File "/home/ocdsdata/ocdsdata/ocdsdata/checks.py", line 48, in check_file
    check_release_row(release_row)
  File "/home/ocdsdata/ocdsdata/ocdsdata/checks.py", line 66, in check_release_row
    cove_output = handle_package(package)
  File "/home/ocdsdata/ocdsdata/ocdsdata/checks.py", line 13, in handle_package
    return ocds_json_output(cove_temp_folder, None, None, convert=False, cache_schema=True, file_type='json', json_data=package)
  File "/home/ocdsdata/ocdsdata/.ve/src/cove/cove_ocds/lib/api.py", line 89, in ocds_json_output
    raise APIException(msg.format(str(list(schema_ocds.version_choices.keys()))))
cove_ocds.lib.api.APIException: The schema version in your data is not valid. Accepted values: ['1.0', '1.1']
```

Looking at one of the Oz files, i see

> "version":1.0

Does the lack of quotes mean it's coming in as an int, and then that doesn't match the string "1.0"???

Maybe we can't fix that, but at least we need to make sure our check process doesn't crash. Catch the 
cove_ocds.lib.api.APIException exception and log it properly.

**Comment by odscjames** [comment]
Ok, we now have a fix in so that it won't crash at least. But can we do better?

Should we convert floats to strings (and log that somewhere)?

I am also reporting elsewhere so this gets passed to publisher.

**Comment by robredpath** [comment]
I think the ideal is "fix and report" on a per-row level in the database - my understanding is that we'd like to be able to do queries of the form "SELECT * FROM records WHERE validation_errors LIKE "%version%"" 

^^ @timgdavies @duncandewhurst ?

**Comment by timgdavies** [comment]
Interesting case.

So - the validator is quite strict about the structure of version numbers (justifiably so). E.g. you can't validate with "1.1.1": http://standard.open-contracting.org/validator/data/7f782b78-6599-46d5-9324-9f767714cd4d 

In terms of what a validation stage of OCDSData pipeline should do if it encounters:

* (a) An invalid version number (e.g. `"1.1.1"`)
* (b) An invalid data type for a version number (e.g. `1.1`) 

I think we have two main choices:

* (1) Fix the error (either (a) and (b), or only (b))  and log
* (2) Log the error, but don't fix it (i.e. further validation would not take place)

I'm thinking that opting for (2) might be preferable **if** we can have a way of overriding the validator version used. This would be useful in two cases:

* Where the publisher can't fix this part of their data right now, but we want to give them feedback on other parts of their data;
* Where a publisher wants to know how much work they would need to do in order to get  their data ready for a future version of OCDS (e.g. we purposely want to validate a 1.0 file against 1.1 to see what would need to change to become valid).

Does this sounds like it would be possible? I guess it might mean we want to always have a column in our validation_errors data for the version the validation took place against (and the date it took place, in case we've added new checks etc. since that time)

**Comment by odscjames** [comment]
Pull request #160 deals with Tim's first user case by specifically fixing Australia.

**Comment by odscjames** [comment]
Pull request #162 deals with Tim's second user case by adding a special option to do that.
