### ISSUE TITLE
Document / check configurations for Unicode

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/ocdsdata#94]
I've set up an instance of ocdsdata-cli on a clean Ubuntu 18.04 with Postgres 10.

Loading a sample of uganda data works correctly, but trying with other countries (e.g. Montreal), I get a Unicode error:

> Unicode escape values cannot be used for code point values above 007F when the server encoding is not UTF8.

A full output is below. I've checked the locale set on the server, and have ensured this is now all 'en_US.utf8' as below:

```
$ locale
LANG=en_US.utf8
LANGUAGE=
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8
```

I've dropped and recreated the database since changing locale, but get the same issue.  

I think this might be about just making sure database is originally created as UTF8, which might need some updates to the readme - but also something to watch in any deployment scripts. 

Full error message.

```
We will run:
 - canada_montreal
Sample mode is on!
Now running: canada_montreal (Output Dir: canada_montreal_sample, Data Version: 2018-06-06-14-09-32)
 - gathering ...
 - fetching ...
 - storing ...
Traceback (most recent call last):
  File "/home/ocdsdata/ocdsdata/.ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/ocdsdata/ocdsdata/.ve/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.DataError: unsupported Unicode escape sequence
LINE 1: ...data) VALUES ('dd5dd03b2ceb3b0f018a2e46d72ec54a', '{"publish...
                                                             ^
DETAIL:  Unicode escape values cannot be used for code point values above 007F when the server encoding is not UTF8.
CONTEXT:  JSON data, line 1: ...la Ville Intelligente", "faxNumber": ""}, "name":...


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ocdsdata/ocdsdata/.ve/bin/ocdsdata-cli", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ocdsdata/ocdsdata/ocdsdata-cli", line 158, in <module>
    main()
  File "/home/ocdsdata/ocdsdata/ocdsdata-cli", line 138, in main
    instance.run_store()
  File "/home/ocdsdata/ocdsdata/ocdsdata/base.py", line 259, in run_store
    database_file.insert_release(row, package_data)
  File "/home/ocdsdata/ocdsdata/ocdsdata/database.py", line 212, in insert_release
    package_data_id = self.get_id_for_package_data(package_data)
  File "/home/ocdsdata/ocdsdata/ocdsdata/database.py", line 234, in get_id_for_package_data
    'data': package_data,
  File "/home/ocdsdata/ocdsdata/.ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/ocdsdata/ocdsdata/.ve/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ocdsdata/ocdsdata/.ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/ocdsdata/ocdsdata/.ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/ocdsdata/ocdsdata/.ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/ocdsdata/ocdsdata/.ve/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ocdsdata/ocdsdata/.ve/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/ocdsdata/ocdsdata/.ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/ocdsdata/ocdsdata/.ve/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.DataError) unsupported Unicode escape sequence
LINE 1: ...data) VALUES ('dd5dd03b2ceb3b0f018a2e46d72ec54a', '{"publish...
                                                             ^
DETAIL:  Unicode escape values cannot be used for code point values above 007F when the server encoding is not UTF8.
CONTEXT:  JSON data, line 1: ...la Ville Intelligente", "faxNumber": ""}, "name":...
 [SQL: 'INSERT INTO package_data (hash_md5, data) VALUES (%(hash_md5)s, %(data)s) RETURNING package_data.id'] [parameters: {'hash_md5': 'dd5dd03b2ceb3b0f018a2e46d72ec54a', 'data': '{"publisher": {"contactPoint": {"url": "http://ville.montreal.qc.ca/", "email": "villeintelligente@ville.montreal.qc.ca", "telephone": "", "name": "B ... (515 characters truncated) ... ": {"count": 232225, "max_value": 98985000.0, "pagination": {"limit": 1000, "offset": 0}, "min_value": -9021474.82, "total_value": 13124399834.7997}}'}] (Background on this error at: http://sqlalche.me/e/9h9h)
```

**Comment by odscjames** [comment]
> CREATE DATABASE ocdsdata WITH OWNER ocdsdata ENCODING 'UTF8'  LC_COLLATE='en_GB.UTF-8' LC_CTYPE='en_GB.UTF-8'  TEMPLATE=template0 ; 

is the command I use. I'll double check and edit the README.

**Comment by odscjames** [comment]
@timgdavies See new Readme - would that have helped, do you think?
